package ua.examples.cxf.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-09-13T10:03:57.421+03:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "UploadServiceEndpointImplService", 
                  wsdlLocation = "file:/home/winter/Projects/java/examples/cxf-file/client/src/main/resources/UploadWS.xml",
                  targetNamespace = "http://server.cxf.examples.ua/") 
public class UploadServiceEndpointImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.cxf.examples.ua/", "UploadServiceEndpointImplService");
    public final static QName UploadServiceEndpointImplPort = new QName("http://server.cxf.examples.ua/", "UploadServiceEndpointImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/winter/Projects/java/examples/cxf-file/client/src/main/resources/UploadWS.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UploadServiceEndpointImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/winter/Projects/java/examples/cxf-file/client/src/main/resources/UploadWS.xml");
        }
        WSDL_LOCATION = url;
    }

    public UploadServiceEndpointImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UploadServiceEndpointImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UploadServiceEndpointImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public UploadServiceEndpointImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UploadServiceEndpointImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UploadServiceEndpointImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns UploadWS
     */
    @WebEndpoint(name = "UploadServiceEndpointImplPort")
    public UploadWS getUploadServiceEndpointImplPort() {
        return super.getPort(UploadServiceEndpointImplPort, UploadWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UploadWS
     */
    @WebEndpoint(name = "UploadServiceEndpointImplPort")
    public UploadWS getUploadServiceEndpointImplPort(WebServiceFeature... features) {
        return super.getPort(UploadServiceEndpointImplPort, UploadWS.class, features);
    }

}
