package ua.examples.cxf.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-09-13T10:03:57.387+03:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://server.cxf.examples.ua/", name = "UploadWS")
@XmlSeeAlso({ObjectFactory.class})
public interface UploadWS {

    @WebMethod
    @RequestWrapper(localName = "uploadFile", targetNamespace = "http://server.cxf.examples.ua/", className = "ua.examples.cxf.server.UploadFile")
    @ResponseWrapper(localName = "uploadFileResponse", targetNamespace = "http://server.cxf.examples.ua/", className = "ua.examples.cxf.server.UploadFileResponse")
    public void uploadFile(
            @WebParam(name = "Dfile", targetNamespace = "")
                    ua.examples.cxf.server.UploadedFile dfile
    );
}
